function text = myupdatefcn(~, event_obj)
    pos = get(event_obj,'Position');
    I = get(event_obj.Target, 'UserData');
    text = {['X: ',num2str(pos(1))],...
            ['Y: ',num2str(pos(2))], ...
            ['Z: ',num2str(pos(3))], ...
            ['Index: ',num2str(I(1))], ...
            ['Id: ',num2str(I(2))]};

end